development:
  adapter: postgresql
  host: ec2-54-225-135-30.compute-1.amazonaws.com
  database: dcqebkv4fq6atp
#  user: biuwcxecsgjums
  port: 5432
  password: KQfR984NW_USjNgSB2xgHF9oRo

test:
  adapter: postgresql
  host: ec2-54-225-135-30.compute-1.amazonaws.com
  database: dcqebkv4fq6atp
#  user: biuwcxecsgjums
  port: 5432
  password: KQfR984NW_USjNgSB2xgHF9oRo

production:
  adapter: postgresql
  host: ec2-54-225-135-30.compute-1.amazonaws.com
  database: dcqebkv4fq6atp
#  user: biuwcxecsgjums
  port: 5432
  password: KQfR984NW_USjNgSB2xgHF9oRo